services:
  database:
    image: mysql:8.4.0
    container_name: knu-80-database
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command:
      --port=${DB_PORT} --max_allowed_packet=32M
    expose:
      - ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: always
    volumes:
      - knu-80-database:/var/lib/mysql
    networks:
      - knu-80-bridge

volumes:
  knu-80-database:

networks:
  knu-80-bridge:
    driver: bridge
