server:
  port: ${SPRING_PORT}
  servlet:
    session:
      timeout: 1800
  tomcat:
    max-connections: 20000
    threads:
      max: 600
      min-spare: 100

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
      connection-timeout: 3000
      validation-timeout: 3000
      idle-timeout: 300000
      max-lifetime: 600000
      keepalive-time: 60000
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_REQUEST_SIZE}
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: ${DDL_AUTO:none}
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        highlight_sql: false
        use_sql_comments: false
  flyway:
    enabled: false
    baseline-on-migrate: false
  threads:
    virtual:
      enabled: true
  devtools:
    restart:
      enabled: false

cors:
  allowed-origins: ${ALLOWED_ORIGINS}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:3600000}

admin:
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ap-northeast-2
      s3:
        bucket: ${AWS_S3_BUCKET}

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  config: classpath:logback/logback-${spring.profiles.active:local}.xml
  file:
    name: ${LOG_FILE_PATH:./logs/app.log}

springdoc:
  packages-to-scan: kr.co.knuserver
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache:
    disabled: true
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    tags-sorter: alpha
    operations-sorter: alpha